name: Update WordPress.org Assets

on:
  push:
    branches:
      - main
    paths:
      - ".wordpress-org/**"
      - "readme.txt"

jobs:
  update_assets:
    name: Push assets and readme to WP.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
